# Generated by Django 5.2.12 on 2026-03-11 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', models.TextField()),
                ('any_fundacio', models.IntegerField(blank=True, null=True)),
                ('zona_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associacions_administrades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=255)),
                ('descripcio', models.TextField()),
                ('data', models.DateTimeField()),
                ('associacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitats', to='core.associacio')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=255)),
                ('contingut', models.TextField()),
                ('data_publicacio', models.DateTimeField(auto_now_add=True)),
                ('associacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticies', to='core.associacio')),
            ],
        ),
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to=settings.AUTH_USER_MODEL)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to='core.noticia')),
            ],
        ),
    ]
