# Generated by Django 5.2.12 on 2026-03-19 02:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='associacio',
            old_name='admin',
            new_name='gerent',
        ),
        migrations.AddField(
            model_name='activitat',
            name='adreça',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitat',
            name='hora',
            field=models.TimeField(default=datetime.time(2, 2, 27, 568705)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitat',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitat',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitat',
            name='usuari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activitats_organitzades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticies_publicades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitat',
            name='data',
            field=models.DateField(),
        ),
    ]
