# Generated by Django 5.2.12 on 2026-04-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_admin_associacio_gerent_activitat_adreça_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitat',
            name='pdf_activitat',
            field=models.FileField(blank=True, help_text="PDF explicatiu de l'activitat (màx 2MB)", max_length=255, null=True, upload_to='pdfs_activitats/'),
        ),
    ]
