# Generated by Django 5.2.12 on 2026-05-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activitat_pdf_activitat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhesioEntitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('lluita_o_objectiu', models.CharField(max_length=255)),
                ('contacte', models.EmailField(max_length=255)),
                ('web', models.URLField(blank=True, max_length=255, null=True)),
                ('data_adhesio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdhesioPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(max_length=150)),
                ('any_naixement', models.IntegerField()),
                ('codi_postal', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('professio', models.CharField(blank=True, max_length=150, null=True)),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_adhesio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='associacio',
            name='adreça',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='associacio',
            name='correu',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='associacio',
            name='descripcio_curta',
            field=models.CharField(blank=True, help_text='Breu descripció (màxim 10 paraules)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='associacio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_associacions/'),
        ),
        migrations.AddField(
            model_name='associacio',
            name='web',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
