# Generated by Django 5.2.12 on 2026-07-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adhesioentitat_adhesiopersona_associacio_adreça_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacio',
            name='any_fundacio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='associacio',
            name='descripcio_curta',
            field=models.CharField(blank=True, help_text='Breu descripció (màyim 10 paraules)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='associacio',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
