# Generated by Django 5.2.12 on 2026-07-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_associacio_any_fundacio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacio',
            name='foto_url',
            field=models.URLField(blank=True, help_text="URL d'una imatge externa (ex: Google Drive)", max_length=500, null=True),
        ),
    ]
