# Generated by Django 5.2.12 on 2026-07-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_associacio_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacio',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL del logo de l'entitat (Google Drive)", max_length=500, null=True),
        ),
    ]
