# Generated by Django 5.2.12 on 2026-09-18 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_associacio_logo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associacio',
            name='gerent',
        ),
        migrations.AddField(
            model_name='associacio',
            name='gerents',
            field=models.ManyToManyField(blank=True, help_text='Usuaris que tenen permís per gestionar aquesta associació', related_name='associacions_administrades', to=settings.AUTH_USER_MODEL),
        ),
    ]
